name: Daily Code Execution

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  push:
    # Optionally specify branches if needed
    branches:
      - master  # Change 'main' to the default branch of your repository if it's different

jobs:
  execute-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create JSON for Token
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "data/token.json"  # Specify the path where the JSON file will be created
          json: ${{ secrets.TOKEN_CONFIG_JSON }}  # Use the secret for the JSON content

      - name: Install dependencies for Google API
        run: |
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Execute script
        run: |
          chmod +x script.sh # Make the script executable
          ./script.sh # Run the script
